// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.auto;

//import java.util.concurrent.TimeUnit;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.CommandBase;
//import edu.wpi.first.wpilibj2.command.WaitCommand;
import frc.robot.Constants;
//import frc.robot.subsystems.DriveSubsystem;
import edu.wpi.first.wpilibj2.command.CommandScheduler;

/**
 *
 */
public class AutoCommand extends CommandBase {

    XboxController m_driverController = new XboxController(Constants.DriverControl.driverControllerPort);

    public AutoCommand() {
        System.out.println("Constructing Auto Routine");

    }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        System.out.println("Initializing DriveCommand");
    }

    // Lidar lidarCrab = new Lidar(new DigitalInput(10));

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        System.out.println("Wait, it's all teleop?");
        System.out.println("Always Has Been.");
        CommandScheduler.getInstance().disable(); // disable the robot
    }

}
